require 'algorithms/simple_memory_ops'
require 'algorithms/shifts_and_rotates'
require 'algorithms/addition_and_subtraction'
require 'algorithms/negation'
require 'algorithms/increments_and_decrements'
