system("ragel src/2a03.rl")
system("ragel src/ines.rl")
system("g++ -g -I /usr/include/SDL -I /usr/include/SDL_mixer -lSDL -lSDL_mixer -Wall src/2a03.c src/happiNES.cpp src/ines.c src/pAPU.cpp -o ./happiNES")
#system("g++ -I /usr/include/SDL -I /usr/include/SDL_mixer -lSDL -lSDL_mixer -Wall src/2a03.c src/cpu_instruction_test.cpp src/ines.c src/pAPU.cpp -o ./2a03")
#system("cd tests;ruby run_tests.rb")
#system("rm 2a03")
