require 'stack_ops/TSX_inst'
require 'stack_ops/TXS_inst'
require 'stack_ops/PHA_inst'
require 'stack_ops/PHP_inst'
require 'stack_ops/PLA_inst'
require 'stack_ops/PLP_inst'
require 'stack_ops/stack_specific'
