require 'incs_decs/INC_inst.rb'
require 'incs_decs/INX_inst.rb'
require 'incs_decs/INY_inst.rb'
require 'incs_decs/DEC_inst.rb'
require 'incs_decs/DEX_inst.rb'
require 'incs_decs/DEY_inst.rb'
require 'incs_decs/DCP_inst.rb'
