require 'branches/BCC_inst.rb'
require 'branches/BCS_inst.rb'
require 'branches/BEQ_inst.rb'
require 'branches/BNE_inst.rb'
require 'branches/BMI_inst.rb'
require 'branches/BPL_inst.rb'
require 'branches/BVC_inst.rb'
