require 'status_flag/CLC_inst.rb'
require 'status_flag/SEC_inst.rb'
require 'status_flag/CLV_inst.rb'
require 'status_flag/CLI_inst.rb'
require 'status_flag/SEI_inst.rb'
require 'status_flag/SED_inst.rb'
require 'status_flag/CLD_inst.rb'
